# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('year', models.ImageField(upload_to='')),
                ('month', models.ImageField(upload_to='')),
                ('number', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'achievement',
            },
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('current_age', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'baby',
            },
        ),
        migrations.CreateModel(
            name='BabyAchievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=None)),
                ('is_activate', models.BooleanField(default=False)),
                ('id_achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MamBook.Achievement')),
                ('id_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MamBook.Baby')),
            ],
            options={
                'db_table': 'baby-achievement',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csrf_token', models.CharField(max_length=255)),
                ('current_version_progress', models.CharField(max_length=100)),
                ('current_version_achievement', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('do_advice', models.TextField()),
                ('not_do_advice', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MamBook.Category')),
            ],
            options={
                'db_table': 'progress',
            },
        ),
        migrations.CreateModel(
            name='SelfDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('day', models.IntegerField()),
            ],
            options={
                'db_table': 'self-development',
            },
        ),
        migrations.CreateModel(
            name='VersionsControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=128)),
                ('latest_version', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'versions_control',
            },
        ),
        migrations.AddField(
            model_name='baby',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MamBook.Profile'),
        ),
    ]
