# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='year',
            field=models.IntegerField(),
        ),
    ]
