# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamBook', '0002_auto_20160120_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baby',
            old_name='current_age',
            new_name='current_date',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='avatar',
        ),
        migrations.AddField(
            model_name='achievement',
            name='version',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baby',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baby',
            name='months',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baby',
            name='years',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='version',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='version',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selfdevelopment',
            name='version',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
